version: "3"

services:
    app:
        environment:
            NODE_ENV: staging
            HTTP_PORT: 3000
            PORT: 3000
            CORS_ALLOWED_ORIGIN: "*"
            MONGODB_URL: mongodb://database:27017
            MONGODB_DATABASE: dbname_test
